import type { Guide } from "@/db/schema";

const now = new Date("2026-09-01T12:00:00.000Z");

export const sampleGuides: Guide[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "movimiento-seguro-primer-trimestre",
    title: "Movimiento seguro durante el primer trimestre",
    excerpt: "Una guía amable para mantenerte activa, reducir molestias y escuchar tu cuerpo durante las primeras semanas.",
    contentMarkdown: "El primer trimestre trae cambios profundos. El movimiento puede ayudarte a transitar esta etapa con más energía y confianza, siempre que tu equipo de salud no haya indicado lo contrario.\n\n## Principios para comenzar\n\n- Prioriza la regularidad por sobre la intensidad.\n- Busca una respiración cómoda durante toda la sesión.\n- Detente ante dolor, sangrado, mareos o falta de aire inusual.\n\n## Una rutina simple\n\nCombina caminatas suaves, movilidad de cadera, ejercicios de fuerza con tu propio peso y respiración diafragmática. Comienza con 15 minutos y ajusta según cómo te sientas.\n\n> Tu cuerpo no necesita exigencia: necesita acompañamiento, seguridad y progresión.\n\n**Importante:** esta guía es educativa y no reemplaza una evaluación médica individual.",
    coverImageUrl: "/images/maite.png",
    coverImageAlt: "Maite, especialista en movimiento prenatal",
    category: "Embarazo",
    // Las guías iniciales son material editorial pendiente de aprobación de Maite.
    status: "draft",
    featured: true,
    readTime: 6,
    seoTitle: "Movimiento seguro en el primer trimestre",
    seoDescription: "Ejercicios y recomendaciones para moverte con seguridad durante las primeras semanas del embarazo.",
    publishedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "respiracion-consciente-embarazo",
    title: "Respiración consciente para volver a tu centro",
    excerpt: "Tres prácticas breves para disminuir tensión y reconectar contigo y con tu bebé.",
    contentMarkdown: "Respirar de forma consciente crea una pausa real en medio del día. No necesitas experiencia ni equipamiento: solo un lugar cómodo y unos minutos.\n\n## Respiración 4–6\n\nInhala suavemente durante cuatro tiempos y exhala durante seis. Repite entre cinco y ocho ciclos sin forzar.\n\n## Respiración lateral\n\nApoya tus manos en las costillas. Siente cómo se expanden hacia los lados al inhalar y cómo regresan al exhalar.\n\n## Cuándo practicar\n\nÚsala antes de dormir, al comenzar una sesión de movimiento o cuando necesites bajar el ritmo.",
    coverImageUrl: null,
    coverImageAlt: null,
    category: "Bienestar",
    status: "draft",
    featured: true,
    readTime: 4,
    seoTitle: null,
    seoDescription: null,
    publishedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "regreso-amable-movimiento-postparto",
    title: "Un regreso amable al movimiento después del parto",
    excerpt: "Señales, prioridades y pasos progresivos para acompañar tu recuperación sin compararte.",
    contentMarkdown: "El postparto no es una carrera. Antes de volver a entrenar, tu cuerpo necesita recuperar descanso, respiración, movilidad y confianza.\n\n## Empieza por la base\n\n1. Respiración diafragmática.\n2. Conexión suave con el suelo pélvico.\n3. Caminatas breves según tolerancia.\n4. Evaluación profesional antes de aumentar impacto.\n\nCada recuperación es distinta. Ajusta los tiempos a tu parto, tu descanso y las indicaciones de tu equipo de salud.",
    coverImageUrl: null,
    coverImageAlt: null,
    category: "Postparto",
    status: "draft",
    featured: false,
    readTime: 5,
    seoTitle: null,
    seoDescription: null,
    publishedAt: null,
    createdAt: now,
    updatedAt: now,
  },
];
