import type { Guide } from "@/db/schema";

const now = new Date("2026-09-01T12:00:00.000Z");

export const sampleGuides: Guide[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "movimiento-seguro-primer-trimestre",
    title: "Movimiento seguro durante el primer trimestre",
    excerpt: "Una guía amable para mantenerte activa, reducir molestias y escuchar tu cuerpo durante las primeras semanas.",
    contentHtml: "<p>El primer trimestre trae cambios profundos. El movimiento puede ayudarte a transitar esta etapa con más energía y confianza, siempre que tu equipo de salud no haya indicado lo contrario.</p><h2>Principios para comenzar</h2><ul><li>Prioriza la regularidad por sobre la intensidad.</li><li>Busca una respiración cómoda durante toda la sesión.</li><li>Detente ante dolor, sangrado, mareos o falta de aire inusual.</li></ul><h2>Una rutina simple</h2><p>Combina caminatas suaves, movilidad de cadera, ejercicios de fuerza con tu propio peso y respiración diafragmática. Comienza con 15 minutos y ajusta según cómo te sientas.</p><blockquote>Tu cuerpo no necesita exigencia: necesita acompañamiento, seguridad y progresión.</blockquote><p><strong>Importante:</strong> esta guía es educativa y no reemplaza una evaluación médica individual.</p>",
    coverImageUrl: "/images/maite.png",
    coverImageAlt: "Maite, especialista en movimiento prenatal",
    category: "Embarazo",
    status: "published",
    featured: true,
    readTime: 6,
    seoTitle: "Movimiento seguro en el primer trimestre",
    seoDescription: "Ejercicios y recomendaciones para moverte con seguridad durante las primeras semanas del embarazo.",
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "respiracion-consciente-embarazo",
    title: "Respiración consciente para volver a tu centro",
    excerpt: "Tres prácticas breves para disminuir tensión y reconectar contigo y con tu bebé.",
    contentHtml: "<p>Respirar de forma consciente crea una pausa real en medio del día. No necesitas experiencia ni equipamiento: solo un lugar cómodo y unos minutos.</p><h2>Respiración 4–6</h2><p>Inhala suavemente durante cuatro tiempos y exhala durante seis. Repite entre cinco y ocho ciclos sin forzar.</p><h2>Respiración lateral</h2><p>Apoya tus manos en las costillas. Siente cómo se expanden hacia los lados al inhalar y cómo regresan al exhalar.</p><h2>Cuándo practicar</h2><p>Úsala antes de dormir, al comenzar una sesión de movimiento o cuando necesites bajar el ritmo.</p>",
    coverImageUrl: null,
    coverImageAlt: null,
    category: "Bienestar",
    status: "published",
    featured: true,
    readTime: 4,
    seoTitle: null,
    seoDescription: null,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "regreso-amable-movimiento-postparto",
    title: "Un regreso amable al movimiento después del parto",
    excerpt: "Señales, prioridades y pasos progresivos para acompañar tu recuperación sin compararte.",
    contentHtml: "<p>El postparto no es una carrera. Antes de volver a entrenar, tu cuerpo necesita recuperar descanso, respiración, movilidad y confianza.</p><h2>Empieza por la base</h2><ol><li>Respiración diafragmática.</li><li>Conexión suave con el suelo pélvico.</li><li>Caminatas breves según tolerancia.</li><li>Evaluación profesional antes de aumentar impacto.</li></ol><p>Cada recuperación es distinta. Ajusta los tiempos a tu parto, tu descanso y las indicaciones de tu equipo de salud.</p>",
    coverImageUrl: null,
    coverImageAlt: null,
    category: "Postparto",
    status: "published",
    featured: false,
    readTime: 5,
    seoTitle: null,
    seoDescription: null,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];
